/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Jempol
 */
public class addDosen extends javax.swing.JFrame {
    String DataTransfer;
    /**
     * Creates new form addDosen
     */
    public addDosen() {
        initComponents();
    }
    
    public addDosen(String DataTransfer) {
        this.DataTransfer = DataTransfer;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nppDosen = new javax.swing.JTextField();
        namaDosen = new javax.swing.JTextField();
        nidn = new javax.swing.JTextField();
        passDosen = new javax.swing.JTextField();
        LDosen = new javax.swing.JRadioButton();
        PDosen = new javax.swing.JRadioButton();
        alamatDosen = new javax.swing.JTextField();
        emailDosen = new javax.swing.JTextField();
        agamaDosen = new javax.swing.JComboBox<>();
        buatDosen = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(528, 660));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nppDosen.setText("NPP");
        nppDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nppDosenActionPerformed(evt);
            }
        });
        getContentPane().add(nppDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 180, -1));

        namaDosen.setText("Nama Dosen");
        namaDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaDosenActionPerformed(evt);
            }
        });
        getContentPane().add(namaDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 180, 50));

        nidn.setText("NIDN");
        getContentPane().add(nidn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 180, -1));

        passDosen.setText("Kata Sandi");
        getContentPane().add(passDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 180, -1));

        LDosen.setText("L");
        LDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LDosenActionPerformed(evt);
            }
        });
        getContentPane().add(LDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        PDosen.setText("P");
        getContentPane().add(PDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        alamatDosen.setText("Alamat");
        getContentPane().add(alamatDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 180, 60));

        emailDosen.setText("e-mail");
        getContentPane().add(emailDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 180, -1));

        agamaDosen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISLAM", "KRISTEN", "HINDU", "BUDHA", "KONGHUCU", " " }));
        getContentPane().add(agamaDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 120, -1));

        buatDosen.setText("BUAT");
        getContentPane().add(buatDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 603, 60, 30));

        jButton2.setText("Kembali");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image_pckg/form-Dosen.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 450, 560));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 450, 560));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Image_pckg/addProdi2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaDosenActionPerformed

    private void LDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LDosenActionPerformed

    private void nppDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nppDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nppDosenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addDosen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton LDosen;
    private javax.swing.JRadioButton PDosen;
    private javax.swing.JComboBox<String> agamaDosen;
    private javax.swing.JTextField alamatDosen;
    private javax.swing.JButton buatDosen;
    private javax.swing.JTextField emailDosen;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField namaDosen;
    private javax.swing.JTextField nidn;
    private javax.swing.JTextField nppDosen;
    private javax.swing.JTextField passDosen;
    // End of variables declaration//GEN-END:variables
}
