/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Toshiba
 */
public class isiFrom extends javax.swing.JFrame {

    /**
     * Creates new form isiFrom
     */
    public isiFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cariButton = new javax.swing.JButton();
        opsiComboBox = new javax.swing.JComboBox<>();
        idTextField = new javax.swing.JTextField();
        idProdiLabel = new javax.swing.JLabel();
        nimLabel = new javax.swing.JLabel();
        nppLabel = new javax.swing.JLabel();
        namaProdiLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        kataSandiLabel = new javax.swing.JLabel();
        nikLabel = new javax.swing.JLabel();
        tglLahirLabel = new javax.swing.JLabel();
        jKLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        agamaLabel = new javax.swing.JLabel();
        prodiLabel1 = new javax.swing.JLabel();
        dsnPembLabel = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        tambahButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        namaTextField = new javax.swing.JTextField();
        kataSandiTextField = new javax.swing.JTextField();
        nikTextField = new javax.swing.JTextField();
        LRadioButton = new javax.swing.JRadioButton();
        PRadioButton = new javax.swing.JRadioButton();
        alamatTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        agamaComboBox = new javax.swing.JComboBox<>();
        prodiTextField = new javax.swing.JTextField();
        dsnPembTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cariButton.setText("Cari");
        getContentPane().add(cariButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        opsiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prodi", "Dosen", "Mahasiswa", "Tambah Baru" }));
        opsiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opsiComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(opsiComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 230, -1));

        idTextField.setText("id");
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 170, 20));

        idProdiLabel.setText("ID Prodi");
        getContentPane().add(idProdiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        nimLabel.setText("NIM");
        getContentPane().add(nimLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        nppLabel.setText("NPP");
        getContentPane().add(nppLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        namaProdiLabel.setText("Nama Prodi");
        getContentPane().add(namaProdiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        namaLabel.setText("Nama");
        getContentPane().add(namaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        kataSandiLabel.setText("Kata Sandi");
        getContentPane().add(kataSandiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        nikLabel.setText("NIK");
        getContentPane().add(nikLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        tglLahirLabel.setText("Tanggal Lahir");
        getContentPane().add(tglLahirLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jKLabel.setText("Jenis Kelamin");
        getContentPane().add(jKLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        alamatLabel.setText("Alamat");
        getContentPane().add(alamatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        emailLabel.setText("E-Mail");
        getContentPane().add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        agamaLabel.setText("Agama");
        getContentPane().add(agamaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        prodiLabel1.setText("Prodi");
        getContentPane().add(prodiLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, -1, -1));

        dsnPembLabel.setText("Dosen Pembimbing");
        getContentPane().add(dsnPembLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, -1, -1));

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 670, -1, -1));

        tambahButton.setText("Tambah");
        getContentPane().add(tambahButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 670, -1, -1));

        logoutButton.setText("Logout");
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, -1));

        namaTextField.setText("nama");
        getContentPane().add(namaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 180, 30));

        kataSandiTextField.setText("kata sandi");
        kataSandiTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kataSandiTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(kataSandiTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 180, 30));

        nikTextField.setText("nik");
        getContentPane().add(nikTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 180, -1));

        LRadioButton.setText("L");
        getContentPane().add(LRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        PRadioButton.setText("P");
        getContentPane().add(PRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        alamatTextField.setText("alamat");
        getContentPane().add(alamatTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 180, 50));

        emailTextField.setText("email");
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 180, -1));

        agamaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISLAM", "KRISTEN", "KATOLIK", "HINDU", "BUDHA", "KONGHUCU" }));
        agamaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agamaComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(agamaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 160, -1));

        prodiTextField.setText("prodi");
        getContentPane().add(prodiTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 180, -1));

        dsnPembTextField.setText("dosen pembimbing");
        getContentPane().add(dsnPembTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 600, 180, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void kataSandiTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kataSandiTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kataSandiTextFieldActionPerformed

    private void agamaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agamaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agamaComboBoxActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void opsiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opsiComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opsiComboBoxActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(isiFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(isiFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(isiFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(isiFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new isiFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton LRadioButton;
    private javax.swing.JRadioButton PRadioButton;
    private javax.swing.JComboBox<String> agamaComboBox;
    private javax.swing.JLabel agamaLabel;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JTextField alamatTextField;
    private javax.swing.JButton cariButton;
    private javax.swing.JLabel dsnPembLabel;
    private javax.swing.JTextField dsnPembTextField;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel idProdiLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jKLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel kataSandiLabel;
    private javax.swing.JTextField kataSandiTextField;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel namaProdiLabel;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JLabel nikLabel;
    private javax.swing.JTextField nikTextField;
    private javax.swing.JLabel nimLabel;
    private javax.swing.JLabel nppLabel;
    private javax.swing.JComboBox<String> opsiComboBox;
    private javax.swing.JLabel prodiLabel1;
    private javax.swing.JTextField prodiTextField;
    private javax.swing.JButton tambahButton;
    private javax.swing.JLabel tglLahirLabel;
    // End of variables declaration//GEN-END:variables
}
