/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiBeta;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modultugasakhir.*;

/**
 *
 * @author Jempol
 */
@SuppressWarnings("serial")
public class DosenFrame1 extends javax.swing.JFrame {
    private User user = new User();
    private Dosen dosen = new Dosen();
    private Mahasiswa mahasiswa = new Mahasiswa();
    private Judul judul = new Judul();
    private Revisi revisi = new Revisi();
    private Kelayakan kelayakan = new Kelayakan();
    
    /**
     * Creates new form isi_dos
     */
    public DosenFrame1() {
        initComponents();
        hideShowAll(false);
        getAllMahasiswaBimbingan();
        getJudulKelayakanFromDatabase();
    }
    
    public DosenFrame1(User user) {
        setUser(user);
        setDosen(new Dosen().getSingleDatabase(user.getUsername()));
        initComponents();
        hideShowAll(false);
        getAllMahasiswaBimbingan();
        getJudulKelayakanFromDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        revisiTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        revisiTextField = new javax.swing.JTextField();
        revisiButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        judulTable = new javax.swing.JTable();
        revisiInputLabel = new javax.swing.JLabel();
        jadwalSeminarTaButton = new javax.swing.JButton();
        revisiLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        nimNamaComboBox = new javax.swing.JComboBox<>();
        layakCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        revisiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID - Revisi", "Tanggal Revisi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(revisiTable);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DOSEN");

        revisiButton.setText("TAMBAH");
        revisiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revisiButtonActionPerformed(evt);
            }
        });

        judulTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proposal / Tugas Akhir", "ID - Judul", "Deskripsi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        judulTable.setColumnSelectionAllowed(true);
        judulTable.getTableHeader().setReorderingAllowed(false);
        judulTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                judulTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(judulTable);
        judulTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        revisiInputLabel.setText("MASUKKAN REVISI");

        jadwalSeminarTaButton.setText("LIHAT JADWAL SEMINAR");
        jadwalSeminarTaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadwalSeminarTaButtonActionPerformed(evt);
            }
        });

        revisiLabel.setText("LIST REVISI");

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        nimNamaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimNamaComboBoxActionPerformed(evt);
            }
        });

        layakCheckBox.setText("Sudah layak maju?");
        layakCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layakCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(nimNamaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(revisiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(layakCheckBox)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(revisiInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(revisiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(revisiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jadwalSeminarTaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton)
                    .addComponent(nimNamaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(revisiInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(revisiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(revisiButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(revisiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(layakCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jadwalSeminarTaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void judulTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_judulTableMouseClicked
        // TODO add your handling code here:
        String idNamaJudul = (String) judulTable.getValueAt(judulTable.getSelectedRow(), 1);
        StringTokenizer token = new StringTokenizer(idNamaJudul);
        String idJudul = token.nextToken("-");
        getRevisiFromDatabase(idJudul);
        
        setKelayakan(new Kelayakan().getSingleFromJudulDatabase(idJudul));
        boolean bool = true;
        if(getKelayakan().getStatusLayak() != null)
            bool = getKelayakan().getStatusLayak();
        layakCheckBox.setSelected(bool);
        hideRevisi(!bool);
        JadwalSeminar jad = new JadwalSeminar().getSingleIdJudulDatabase(idJudul);
        if(jad.getJadwal()!= null)
            jadwalSeminarTaButton.setVisible(true);
        
    }//GEN-LAST:event_judulTableMouseClicked

    private void revisiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revisiButtonActionPerformed
        // TODO add your handling code here:
        String idNamaJudul = (String) judulTable.getValueAt(judulTable.getSelectedRow(), 1);
        StringTokenizer token = new StringTokenizer(idNamaJudul);
        String idJudul = token.nextToken("-");
        
        setRevisi(new Revisi(idJudul, getDosen().getNpp(), revisiTextField.getText(), new java.util.Date()));
        getRevisi().insertToDatabase();
        getRevisiFromDatabase(idJudul);
        JOptionPane.showMessageDialog(null, "Data Tersimpan");
        hideRevisi(false);
    }//GEN-LAST:event_revisiButtonActionPerformed

    private void layakCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layakCheckBoxActionPerformed
        // TODO add your handling code here:
        String idNamaJudul = (String) judulTable.getValueAt(judulTable.getSelectedRow(), 1);
        StringTokenizer token = new StringTokenizer(idNamaJudul);
        String idJudul = token.nextToken("-");
            
        if(layakCheckBox.isSelected()){
            Kelayakan kel = new Kelayakan(true, idJudul);
            kel.insertToDatabase();
        }
        else{
            new Kelayakan().deleteSingleDatabase(idJudul);
        }
    }//GEN-LAST:event_layakCheckBoxActionPerformed

    private void nimNamaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimNamaComboBoxActionPerformed
        // TODO add your handling code here:
        getJudulKelayakanFromDatabase();
    }//GEN-LAST:event_nimNamaComboBoxActionPerformed

    private void jadwalSeminarTaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadwalSeminarTaButtonActionPerformed
        // TODO add your handling code here:
        String idNamaJudul = (String) judulTable.getValueAt(judulTable.getSelectedRow(), 1);
        StringTokenizer token = new StringTokenizer(idNamaJudul);
        String idJudul = token.nextToken("-");
        
        JadwalSeminar jad = new JadwalSeminar().getSingleIdJudulDatabase(idJudul);
        JOptionPane.showMessageDialog(null, new SimpleDateFormat("dd-MM-yyyy").format(jad.getJadwal()));
    }//GEN-LAST:event_jadwalSeminarTaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DosenFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DosenFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DosenFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DosenFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DosenFrame1().setVisible(true);
            }
        });
    }

    public void hideShowAll(boolean bool){
        jadwalSeminarTaButton.setVisible(bool);
        revisiLabel.setVisible(bool);
        hideRevisi(bool);
    }
    
    public void hideRevisi(boolean bool){
        revisiButton.setVisible(bool);
        revisiInputLabel.setVisible(bool);
        revisiTextField.setVisible(bool);
    }
    
    public void getJudulKelayakanFromDatabase(){
        DefaultTableModel modelTableJudul = (DefaultTableModel) judulTable.getModel();
        modelTableJudul.setRowCount(0);
        Object[] atributJudul = new Object[3];
        try {
            ArrayList<Judul> JudulAll = new Judul().getAllNimDatabase(getSelectedCombo());
            Iterator<Judul> listJudul = JudulAll.iterator();
            while(listJudul.hasNext()){
                Judul eachJudul = listJudul.next();
                atributJudul[0] = eachJudul.getTipeJudul();
                atributJudul[1] = eachJudul.getIdJudul() + "-" + eachJudul.getNamaJudul();
                atributJudul[2] = eachJudul.getDeskripsi();
        
                modelTableJudul.addRow(atributJudul);
            }
            judulTable.setModel(modelTableJudul);
        } catch (Exception ex) {
            Logger.getLogger(MahasiswaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void getRevisiFromDatabase(String idJudul){
        DefaultTableModel modelTableRevisi = (DefaultTableModel) revisiTable.getModel();
        modelTableRevisi.setRowCount(0);
        Object[] atributRevisi = new Object[2];
        try {
            ArrayList RevisiAll = new Revisi().getAllIdJudulDatabase(idJudul);
            Iterator listRevisi = RevisiAll.iterator();
            while(listRevisi.hasNext()){
                Revisi eachRevisi;
                eachRevisi = (Revisi) listRevisi.next();
                atributRevisi[0] = eachRevisi.getIdRevisi() + "-" + eachRevisi.getIsiRevisi();
                atributRevisi[1] = new SimpleDateFormat("dd-MM-yyyy").format(eachRevisi.getTanggalRevisi());
        
                modelTableRevisi.addRow(atributRevisi);
            }
            revisiTable.setModel(modelTableRevisi);
        } catch (Exception ex) {
            Logger.getLogger(MahasiswaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void getAllMahasiswaBimbingan(){
        ArrayList<Mahasiswa> allMahasiswa = new Mahasiswa().getAllDatabase("");
        Iterator listMahasiswa = allMahasiswa.iterator();
        while(listMahasiswa.hasNext()){
            Mahasiswa maha = (Mahasiswa) listMahasiswa.next();
            if(maha.DosenPembimbingMahasiswa.getNpp().equals(getDosen().getNpp())){
                nimNamaComboBox.addItem(maha.getNim() + "-" + maha.getNama());
            }
        }
    }
    
    public String getSelectedCombo(){
        String pilih = nimNamaComboBox.getSelectedItem().toString();
        StringTokenizer token = new StringTokenizer(pilih);
        return token.nextToken("-");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jadwalSeminarTaButton;
    private javax.swing.JTable judulTable;
    private javax.swing.JCheckBox layakCheckBox;
    private javax.swing.JButton logoutButton;
    private javax.swing.JComboBox<String> nimNamaComboBox;
    private javax.swing.JButton revisiButton;
    private javax.swing.JLabel revisiInputLabel;
    private javax.swing.JLabel revisiLabel;
    private javax.swing.JTable revisiTable;
    private javax.swing.JTextField revisiTextField;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the user
     */
    public User getUser() {
        return user;
    }

    /**
     * @param user the user to set
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * @return the dosen
     */
    public Dosen getDosen() {
        return dosen;
    }

    /**
     * @param dosen the dosen to set
     */
    public void setDosen(Dosen dosen) {
        this.dosen = dosen;
    }

    /**
     * @return the mahasiswa
     */
    public Mahasiswa getMahasiswa() {
        return mahasiswa;
    }

    /**
     * @param mahasiswa the mahasiswa to set
     */
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }

    /**
     * @return the judul
     */
    public Judul getJudul() {
        return judul;
    }

    /**
     * @param judul the judul to set
     */
    public void setJudul(Judul judul) {
        this.judul = judul;
    }

    /**
     * @return the revisi
     */
    public Revisi getRevisi() {
        return revisi;
    }

    /**
     * @param revisi the revisi to set
     */
    public void setRevisi(Revisi revisi) {
        this.revisi = revisi;
    }

    /**
     * @return the kelayakan
     */
    public Kelayakan getKelayakan() {
        return kelayakan;
    }

    /**
     * @param kelayakan the kelayakan to set
     */
    public void setKelayakan(Kelayakan kelayakan) {
        this.kelayakan = kelayakan;
    }
}
