/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiBeta;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modultugasakhir.*;

/**
 *
 * @author Ajeng
 */
public class MahasiswaFrame1 extends javax.swing.JFrame {
    private User user = new User();
    private Mahasiswa mahasiswa = new Mahasiswa();
    /**
     * Creates new form Mahasiswa
     */
    public MahasiswaFrame1() {
        initComponents();
        hideAll(false);
    }

    
    public MahasiswaFrame1(User user) {
        setUser(user);
        setMahasiswa(new Mahasiswa().getSingleDatabase(user.getUsername()));
        initComponents();
        hideAll(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutButton = new javax.swing.JButton();
        namaMahasiswa = new javax.swing.JLabel();
        tambahJudul = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RevisiTable = new javax.swing.JTable();
        jadwalButton = new javax.swing.JButton();
        tipeJudulComboBox = new javax.swing.JComboBox<>();
        judulLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoutButton.setText("LOGOUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        namaMahasiswa.setText("Hai,");

        tambahJudul.setText("AJUKAN JUDUL");
        tambahJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahJudulActionPerformed(evt);
            }
        });

        RevisiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Revisi", "Tanggal Revisi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        RevisiTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(RevisiTable);

        jadwalButton.setText("LIHAT JADWAL SEMINAR");

        tipeJudulComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Judul-", "Proposal", "Tugas Akhir" }));
        tipeJudulComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipeJudulComboBoxActionPerformed(evt);
            }
        });

        judulLabel.setText("Judul : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(399, Short.MAX_VALUE)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(tipeJudulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tambahJudul)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judulLabel)
                            .addComponent(namaMahasiswa)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jadwalButton)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaMahasiswa)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahJudul)
                    .addComponent(tipeJudulComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(judulLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jadwalButton)
                .addGap(137, 137, 137)
                .addComponent(logoutButton)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahJudulActionPerformed
        // TODO add your handling code here:
        Judul jud = new Judul(getMahasiswa().getNim(), JOptionPane.showInputDialog(null, "Masukkan Judul", "Judul", 3), JOptionPane.showInputDialog(null, "Masukkan Deskripsi", "Deskripsi", 3), tipeJudulComboBox.getSelectedItem().toString());
        jud.insertToDatabase();
    }//GEN-LAST:event_tambahJudulActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void tipeJudulComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipeJudulComboBoxActionPerformed
        // TODO add your handling code here:
        tambahJudul.setVisible(false);
        jadwalButton.setVisible(false);
        ArrayList<Judul> AllJudul = new Judul().getAllDatabase("");
        Iterator<Judul> listJudul = AllJudul.iterator();
        boolean cek = true;
        switch (tipeJudulComboBox.getSelectedItem().toString()){
            case "Proposal" :
            {
                while(listJudul.hasNext()){
                    Judul judul = listJudul.next();
                    if((judul.MahasiswaDalamJudul.getNim().equals(getMahasiswa().getNim())) && (judul.getTipeJudul().equals("Proposal"))){
                        tambahJudul.setVisible(false);
                        judulLabel.setVisible(true);
                        judulLabel.setText("Judul Proposal : " + judul.getNamaJudul());
                        getRevisiFromDatabase(judul.getIdJudul());
                        JadwalSeminar jad = new JadwalSeminar().getSingleIdJudulDatabase(judul.getIdJudul());
                        if(jad.getJadwal() != null)
                            jadwalButton.setVisible(true);
                        cek = false;
                        break;
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Anda belum mengajukan Judul Proposal!");    
                    }
                    
                }
                if (cek){
                    tambahJudul.setVisible(true);
                    judulLabel.setVisible(false);
                }
                break;
            }
            case "Tugas Akhir" :
            {
                while(listJudul.hasNext()){
                    Judul judul = listJudul.next();
                    if((judul.MahasiswaDalamJudul.getNim().equals(getMahasiswa().getNim())) && (judul.getTipeJudul().equals("Tugas Akhir"))){
                        tambahJudul.setVisible(false);
                        judulLabel.setText("Judul Tugas Akhir : " + judul.getNamaJudul());
                        getRevisiFromDatabase(judul.getIdJudul());
                        JadwalSeminar jad = new JadwalSeminar().getSingleIdJudulDatabase(judul.getIdJudul());
                        if(jad.getJadwal() != null)
                            jadwalButton.setVisible(true);
                        cek = false;
                        break;
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Anda belum mengajukan Judul Tugas Akhir!");
                        
                    }
                }
                if (cek){
                    tambahJudul.setVisible(true);
                    judulLabel.setVisible(false);
                }
                break;
            }
            default :
            {
                tambahJudul.setVisible(false);
                JOptionPane.showMessageDialog(null, "Pilih tipe judul!");
                
            }
        }
        
    }//GEN-LAST:event_tipeJudulComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MahasiswaFrame1().setVisible(true);
            }
        });
    }
    
    public void getRevisiFromDatabase(String idJudul){
        DefaultTableModel modelTableRevisi = (DefaultTableModel) RevisiTable.getModel();
        modelTableRevisi.setRowCount(0);
        Object[] atributRevisi = new Object[2];
        try {
            ArrayList RevisiAll = new Revisi().getAllIdJudulDatabase(idJudul);
            Iterator listRevisi = RevisiAll.iterator();
            while(listRevisi.hasNext()){
                Revisi eachRevisi;
                eachRevisi = (Revisi) listRevisi.next();
                atributRevisi[1] = eachRevisi.getIsiRevisi();
                atributRevisi[2] = new SimpleDateFormat("dd-MM-yyyy").format(eachRevisi.getTanggalRevisi());
        
                modelTableRevisi.addRow(atributRevisi);
            }
            RevisiTable.setModel(modelTableRevisi);
        } catch (Exception ex) {
            Logger.getLogger(MahasiswaFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void hideAll(boolean bool){
        jadwalButton.setVisible(bool);
        judulLabel.setVisible(bool);
        tambahJudul.setVisible(bool);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RevisiTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jadwalButton;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel namaMahasiswa;
    private javax.swing.JButton tambahJudul;
    private javax.swing.JComboBox<String> tipeJudulComboBox;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the user
     */
    public User getUser() {
        return user;
    }

    /**
     * @param user the user to set
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * @return the mahasiswa
     */
    public Mahasiswa getMahasiswa() {
        return mahasiswa;
    }

    /**
     * @param mahasiswa the mahasiswa to set
     */
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }
}
